# Generated by Django 5.2.13 on 2026-04-29 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='aritcle',
            new_name='article',
        ),
    ]
